{% set name = "matplotlibhelper" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa4e62afbf7875b50b08f83929c5ac885a72c208078ab4ddeb97f8f771f0d45c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - ipython
    - sugartex >=0.1.16
    - matplotlib

test:
  imports:
    - matplotlibhelper

about:
  home: https://github.com/kiwi0fruit/matplotlibhelper
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Matplotlib Helper is my custom helper to tune Matplotlib experience in Atom/Hydrogen and Pandoctools/Knitty."
  doc_url: https://github.com/kiwi0fruit/matplotlibhelper
  dev_url: https://github.com/kiwi0fruit/matplotlibhelper

extra:
  recipe-maintainers:
    - kiwi0fruit
